poll/urls.py
from django.urls import include, path
# from django.urls import path

from . import views

app_name = 'poll'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.results, name='results'),
    path('vote/', views.vote, name='vote'),
    path('uloz/', views.uloz, name='uloz'),
    # path('apiapp/', views.ApiAppView.as_view(), name='apiapp'),
    # path('databaseApp/', views.databaseApp, name='databaseApp'),
    # path('twitterApp/', views.twitterapp, name='twitterapp'),
    path('changeapp/', views.changeApp, name='changeapp'),
    path('changeDlazdice/', views.changeDlazdice, name='changeDlazdice'),
    path('changePagin/', views.changePagin, name='changePagin'),
    path('get_name/', views.get_name, name='get_name'),
    # path('forms/', views.forms, name='forms'),

    # path('changeDlazdice/<int:question_type>', views.changeDlazdice, name='changeDlazdice'),
    # path("select2/", include("django_select2.urls")),
    # path("book/create", views.BookCreateView.as_view(), name="book-create"),
    
    path("modal_window/", views.modal_window, name="modal_window"),
]

portfolio/urls.py
import logging

logger = logging.getLogger("AppPoll")
logger.info("poll urls ----")


from django.contrib import admin
from django.urls import include, path
# from poll import views

urlpatterns = [
    path('', include('mujweb.urls')),
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    
]

poll/models.py
from django.db import models

from django.conf import settings
import pdb

# Create your models here.

class Users(models.Model):
    jmeno = models.CharField(max_length = 20)
    mail_address = models.CharField(max_length = 40, default = None)

    def __str__(self):
        return self.jmeno

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    question_type = models.IntegerField(default=1)
    pokus = 'pokus'

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class MojeOdkazy1(models.Model):
    # pdb.set_trace()
    key = models.CharField(max_length=45, blank=True, null=True)
    value = models.CharField(max_length=200, blank=True, null=True)
    xxx = 'xxxxxxx'

    class Meta:
        managed = False
        db_table = 'moje_odkazy_1'
        verbose_name='Odkazy'
    
    def __str__(self):
        #  return '%s %s' % (self.key, self.value)
        odkaz = str({'key': self.key, 'value': self.value})
        return odkaz

poll/forms.py
from django import forms
# from django_select2 import forms as s2forms

from . import models
# from .models import MojeOdkazy1


class NameForm(forms.Form):
    # jmeno = forms.CharField(label='Your name', max_length=100)
    # mail_address = forms.CharField(label='E-mail Adrress', max_length=100)
    first_name = forms.CharField(label='First name', max_length=100)
    last_name = forms.CharField(label='Last name', max_length=100)
    email = forms.CharField(label='E-mail Adrress', max_length=100)





# class KeyWidget(s2forms.ModelSelect2Widget):
#     search_fields = [
#         "username__icontains",
#         "email__icontains",
#     ]


# class ValueWidget(s2forms.ModelSelect2MultipleWidget):
#     search_fields = [
#         "username__icontains",
#         "email__icontains",
#     ]

# class BookForm(forms.ModelForm):
#     class Meta:
#         model = models.MojeOdkazy1
#         fields = "__all__"
#         widgets = {
#             "author":  KeyWidget,
#             "co_authors": ValueWidget,
#             # 'xxx': XxxWidget,
#             # 'myfield': forms.TextInput(attrs={'class': 'myfieldclassXXX'}),
#         }


# class MyForm(forms.ModelForm):
#     class Meta:
#         model = MyModel
#         widgets = {
#             'myfield': forms.TextInput(attrs={'class': 'myfieldclass'}),
#         }

poll/views.py
from django.shortcuts import  get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, HttpResponse
from django.urls import reverse
from django.views import generic
import logging
import json
from .models import Question, Choice, MojeOdkazy1, Users
import requests
import time
from django.views.generic import ListView
from django.core.paginator import Paginator
import pdb
from . import forms, models
# from .forms import NameForm, BookForm
import random
import string

from django.core.mail import send_mail
from django.conf import settings

from django.contrib.auth.models import User
#regular expressions
import re
from django.contrib.auth.models import Permission
from django.template import loader
import base64
from .forms import NameForm


def modal_window(request):

    if request.method == 'GET':
        # pdb.set_trace()

        #TODO - Try:
        title = request.GET['title'].upper()
        url = request.GET['url']

        #získáme obrázek, převedeme na base64
        # URL = url
        r = requests.get(url)
        image = r.content
        encoded_string = base64.b64encode(image)
        file = 'data:image/png;base64,'  + str(encoded_string.decode('utf-8'))


        context = {
            'title': title,
            'url': url,
            'image': file
        }

    return render(request,'components/modal_window.html', context)

def get_name(request):
    logger = logging.getLogger("AppPoll")
    logger.info("get name 1")
    regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'

    if request.method == 'POST':
        form =  json.loads(request.POST['formData'])
        try:
            first_name = form['first_name']
            last_name = form['last_name']
            email = form['email']

        except (KeyError, Choice.DoesNotExist):
            return render(request,'poll/forms.html',{'message': 'Not valid inputs. Click Form and try it again. No data available.'})

        else:
            def checkEmail(email):
                if(re.search(regex,email)):
                    #"Valid Email"
                    return True
                else:
                    #"Invalid Email"
                    return False

            #kontrola, zda ve jmenech není číslovka
            def hasNumbers(inputString):
                return bool(re.search(r'\d', inputString))
            first_name_hasNum = hasNumbers(first_name)
            last_name_hasNum = hasNumbers(last_name)

            def inputCheck(inputString):
                if '<' in inputString or '>' in inputString or "'" in inputString or '"' in inputString or ' ' in inputString:
                    return False

            form_isValid = True;
            if (first_name == '' or first_name_hasNum == True or last_name_hasNum == True or last_name == '' or checkEmail(email) == False or inputCheck(first_name) == False or inputCheck(last_name) == False):
                form_isValid = False;


            if form_isValid:
                # vytvoř heslo
                password = ''
                for i in range(5):
                    num = random.randint(0, 9)
                    letter = random.choice(string.ascii_letters)
                    password += str(num)
                    password += letter

                #kontrola, zda není již stejné username v db, username je email
                num_results = User.objects.filter(username = email).count()

                if(num_results < 1 ):
                    logger.info("get name 2")
                    #vytváříme usera, první argument je username, musí být unikátní
                    user = User.objects.create_user(email)
                    # user = User.objects.get(username = 'kamil')
                    logger.info("get name 3")
                    user.first_name = first_name
                    user.last_name = last_name
                    # user.username = form['last_name']
                    logger.info("get name 4")
                    user.email = email
                    #heslo se hashuje
                    logger.info("get name 5")
                    user.set_password(password)
                    # is_staff = 1, user může do admin sekce
                    logger.info("get name 6")
                    user.is_staff = True
                    logger.info("get name 7")
                    
                    # permission = Permission.objects.get(name='Can view Odkazy')
                    
                    #TODO: Can view question je v polls i poll - odlišit
                    logger.info("get name 8")
                    
                    # permission2 = Permission.objects.get(name='Can view question')
                    
                    logger.info("get name 9")
                    # user.user_permissions.add(permission, permission2)
                    logger.info("get name 10")

                    user.save()

                    html_message = loader.render_to_string(
                        'poll/email_template.txt',
                        {
                            'user_name': user.first_name + ' ' + user.last_name,
                            'subject':   password,

                        }
                    ).strip()

                    logger.info("get name 11")

                    #posleme email
                    # send_mail(
                    #     subject = 'Automatically generated e-mail. JS webpages code.',
                    #     # message = '<p>Here is your security code:<h3> ' + password + ' <h3>. Write it into the log-in input.',
                    #     message = html_message,
                    #     from_email = "janslajchrt81@gmail.com",
                    #     recipient_list = [email,],
                    #     auth_user = 'janslajchrt81@gmail.com',
                    #     auth_password = 'Lmrlmrlmr111',
                    #     fail_silently = False,
                    #     )

                    send_mail(
                        subject = 'Automatically generated e-mail. JS webpages code.',
                        # message = '<p>Here is your security code:<h3> ' + password + ' <h3>. Write it into the log-in input.',
                        message = html_message,
                        from_email = "3006@rostiapp.cz",
                        recipient_list = [email,],
                        auth_user = '3006@rostiapp.cz',
                        auth_password = '179fb6ef67e84625ad7bf402a8a8a321',
                        fail_silently = False,
                        )
                    logger.info("get name 12") 
                else:
                     return render(request,'poll/forms.html',{'message': 'You are already registered.'})
                # return HttpResponseRedirect('http://localhost:8000/admin')
                return HttpResponseRedirect('http://localhost:8000/admin/login/?next=/admin/')
                # return render(request,'poll/forms.html',{'message': 'You can log in to administration sites under the password in your e-mail.'})
            else:
                return render(request,'poll/forms.html',{'message': 'Not valid inputs. Click Form and try it again.'})
    else:
        form = NameForm()
        # return render(request,'poll/forms.html',{'message': 'Not valid inputs. Try it again.'})

    # return render(request, 'poll/forms.html', {'form': form})


# class BookCreateView(generic.CreateView):
#     template_name = 'poll/proj/select.html'
#     model = models.MojeOdkazy1
#     # pdb.set_trace()
#     form_class = forms.BookForm
#     success_url = "/"
#     id_dlazdice = None

#     URL = "https://jsonplaceholder.typicode.com/photos/"
#     r = requests.get(url = URL)
#     data = r.json()
#     # pdb.set_trace()
#     context = {'data':data}


logger = logging.getLogger("AppPoll")
logger.info("Whatever to log")

question_type = None

# meni dlazdice z hlavni listy
def changeApp(request):
    logger = logging.getLogger("AppPoll")

    if request.method == 'GET':
        id_dlazdice = request.GET['id_dlazdice']
        logger.info("IDDDDDDDDDDDDDD type in get----- ")
        logger.info("ID DLAZKA get " + id_dlazdice)

        if id_dlazdice == "index1":
            # question_type = request.GET['question_type']
            question_type = 1
            logger = logging.getLogger("AppPoll")
            logger.info("Get konec APIAPPPPP" + 'po po pio 11111')
            context = {}
            logger.info(str(context))
            return render(request, 'poll/apiapp.html', context)
        elif id_dlazdice == "index2":
            # question_type = request.GET['question_type']
            question_type = 1
            logger = logging.getLogger("AppPoll")
            logger.info("Get konec index 2 question type" + str(question_type))
            context = {'list':{'latest_question_list':Question.objects.filter(question_type = question_type).order_by('pk')[:5], 'choice_list': Choice.objects.all(), 'question_type': question_type}}
            logger.info("Get konec " + str(context))
            return render(request, 'poll/poll.html', context)
        elif id_dlazdice == "index3":
            logger.info("Index 3 -- 1 ")
            form = NameForm()
            logger.info("Index 3 -- 2 ")
            context = {'form':form}
            # return render(request, 'poll/forms.html', context)
            return render(request, 'components/login_admin_form.html', context)


#paginator je v database app
def changePagin(request):
    odkazy = MojeOdkazy1.objects.all()
    # logger.info("Pagin 1 -------------- ")
    paginator = Paginator(odkazy, 2) # Show 2 contacts per page.
    # logger.info("Pagin 1 pagggii object list-------------- " + str(paginator.object_list))

    page_number = request.GET.get('pageNum')
    # pdb.set_trace()
    page_obj = paginator.get_page(page_number)
    # return render(request, 'poll/proj/databaseApp.html', {'page_obj': page_obj})

poll/templates/components/login_admin_form.html
<style>
    #login_form{
        display:flex;
        flex-direction: column;
        align-items: baseline;
        padding: 3px;
    }

    input, label{
        margin: 5px;
    }

    #submit{
        width: 6em;
        margin: 5px;
    }

   
.nadpis{
    font-family: calibri;
}

</style>


<div class="modal"><!-- Spinner --></div>
<h2>Administrative account Sign-in</h2>
<div class="nadpis">Your e-mail address will never be used for any other purpose than this app.</div>
<div class="nadpis">Username for admin sites is the e-mail address you provided here.</div>
<div class="nadpis">After sending the login details you will be redirected to login page or you can login <a href="http://localhost:8000/admin" target="_blank">here </a>.</div>
<div class="nadpis">You can check some models in administrative section, but you can´t make any changes there.</div>
<div class="nadpis">Serves only as an example.</div>
<div class="nadpis">Check your e-mails for password.</div>
<div class="nadpis">All fields in form below are required.</div>

{% comment %} <form id="login_form" action="/poll/get_name/" method="post"> {% endcomment %}
<form id="login_form">
    {% csrf_token %}
    {{ form }}
    {% comment %} <input type="submit" value="Submit"> {% endcomment %}
    {% comment %} <a type="button" id="submit" class="button" target = "_blank" href="http://localhost:8000/admin/">Submit</a> {% endcomment %}
    <button id="submit" class="button">Submit</button>
</form>

<script>
$(document).ready(function(){
    console.log('submit');
    $('#submit').on('click', function(e){
        e.preventDefault();
        
        $('.modal').show();

        var form = $('#login_form');
        var formData = {}

        const first_name = form.find("input[name='first_name']").val();
        const last_name = form.find("input[name='last_name']").val();
        const email = form.find("input[name='email']").val();
        formData['first_name'] = first_name; 
        formData['last_name'] = last_name; 
        formData['email'] = email; 

        console.log('Form data ', formData);
        
         $.ajax({
            type: 'POST',
            url: '/poll/get_name/',
            data:{
                formData:JSON.stringify(formData),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(data){
                $('#appContent').html(data);
            }
        });
    });

});

</script>

poll/templates/components/modal_window.html
<div class="pozadi">
    <div class="modal_window">
    <div class="close"></div>
        <div class = "headder_mo">
        </div>
        <div class = "body_mo">
            <div class="nadpisy">
                <div class = "title_mo_photo" style="display:flex; flex-direction: row"><span class="pic_name_key">Picture name: </span> <div class="pic_name_val">{{title}}</div></div>
                <div class = "title_mo_photo"><span class="pic_name_key">Picture url: </span> <span class="pic_name_val"><a href={{url}} target="_blank">{{url}}</a></span></div>
            </div>
            <img style="-webkit-user-select: none;margin: auto;" src={{image}}>
            {% comment %} <img style="-webkit-user-select: none;margin: auto;" src={{url}}> {% endcomment %}
        </div>
        <div class = "footer_mo">
        </div>
    </div>
<div>

<script>
    $(document).ready(function(){
        $('.close').on('click', function(){
            $('.pozadi').remove();
        });
    });

</script>

poll/templates/components/paginator1.html
    <style>
        .pagin_item{
            font-size: 18px;
            margin: 5px;
        }
        .pagin_item:hover{
            font-size: 22px;
        }
    </style>
    
    <script>console.log('paginatorrrrr---')</script>

    <div class="modal"><!-- Spinner --></div>

    <div class="pagin_content" style="margin-bottom: 15px;">
        {% for odkaz in page_obj %}
            <div class="row"><a target="_blank" href ="{{odkaz.value}}"><span class="pagin_item">{{odkaz.key}}</span></a></div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <button class="pagin" id="paginFirst">&laquo; first</button>
                <button class="pagin" id="paginPrevious" >previous</button>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                {% comment %} <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endcomment %}

                <button class="pagin" id="paginNext">next</button>
                <button class="pagin" id="paginLast">last &raquo;</button>

            {% endif %}
        </span>
    </div>
    
    <script type="text/javascript"> 
        $(document).ready(function(){
            $('.pagin').on('click', function(){
                
                $('.modal').show();

                const id = $(this).attr('id')
                var pageNum = 0;
                switch (id){
                    case 'paginNext':
                    pageNum = "{{ page_obj.next_page_number }}";
                    break;
                    case 'paginLast':
                    pageNum = "{{ page_obj.paginator.num_pages }}";
                    console.log('Pagin last ', pageNum );
                    break;
                    case 'paginPrevious':
                    pageNum = "{{ page_obj.previous_page_number }}";
                    break;
                    case 'paginFirst':
                    pageNum = 1;
                }
                
                $.ajax({
                    type:'GET',
                    url: '/poll/changePagin',
                    data: {
                        id_dlazdice: 'dlazdiceApiApp' + 1,
                        pageNum: pageNum
                    },
                    success: function (data) {
                        $('.paginator').html(data);
                    }
                    });
                });

        });
    </script>

poll/templates/components/radio_button.html
{% comment %} {% extends 'index.html' %} {% endcomment %}
    {% comment %} {{list}} {% endcomment %}
    {% comment %} {{list.latest_question_list}} {% endcomment %}
    <style>
    ._row{
        margin:5px;
        padding: 2px 5px;

        background: rgba(255,255,255,1);
        background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(255,255,255,1)), color-stop(19%, rgba(255,255,255,1)), color-stop(49%, rgba(240,240,240,1)), color-stop(78%, rgba(250,250,250,1)), color-stop(100%, rgba(250,250,250,1)));
        background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -o-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -ms-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#fafafa', GradientType=0 );
    }
    
    </style>

    {% if list.latest_question_list %}
        <div class = "polls" style="width:max-content">
            <h1>Poll</h1>
            {% comment %} <form action="{% url 'poll:vote' %}" method="post" class="_poll" id='{{list.question_type}}'> {% endcomment %}

            <div class "_form" id='{{list.question_type}}'>


            {% csrf_token %}
                
                <input type='hidden' value='{{list.question_type}}' name='question_type'> 

                {% for question in list.latest_question_list %}
                    <div class="_row" style="width:max-content">{{ question.question_text }} |xx|
                        <span class = "_choices">                     
                            {% for choice in list.choice_list %}
                                {% if  choice.question.id == question.id %}
                                    <span class = "_choice" >
                                        <input class = "_radioBtn" type="radio" name="choiceForQuestion_{{question.id}}" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                                    </span>
                                {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                {% endfor %}
                {% comment %} <input type="submit" value="Vote"> {% endcomment %}
                <button id="submit" value="Vote">Vote</button>


            </div>
        </div>

        <script>
            $(document).ready(function(){
                {% comment %} var form_id = $('form').attr('id'); {% endcomment %}

                var form_id = $('._form').attr('id');
                var opakovani = 0;

                $('#submit').on('click', function(e){
                    e.preventDefault();
                    question_type = {{list.question_type}}
                    var formData = {}

                    $('._row').find('._radioBtn').each(function(){
                        if ( $(this).is(':checked') ) { 
                            console.log('Checked name' , this.name) 
                            console.log('Checked value' , this.value)
                            formData[this.name] = this.value; 
                            }
                    });

                    console.log('formData ', formData);
                    console.log('Submitttttt question type: ', question_type);

                    $.ajax({
                        type:'POST',
                        url: '/poll/uloz/',
                        data: {
                            question_type: question_type,
                            formData:JSON.stringify(formData),
                            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                            },
                        success: function(response){
                            $('#appContent').html(response);

                        }
                    });

                });     
            });
        </script>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

poll/templates/components/results.html
<style>
    .results{
        margin: 5px;
    }
    .result_text{
        font-size: 22px;
    }
    ._row_results{
        margin:5px;
        padding: 2px 5px;

        background: rgba(255,255,255,1);
        background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(255,255,255,1)), color-stop(19%, rgba(255,255,255,1)), color-stop(49%, rgba(240,240,240,1)), color-stop(78%, rgba(250,250,250,1)), color-stop(100%, rgba(250,250,250,1)));
        background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -o-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: -ms-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        background: linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 19%, rgba(240,240,240,1) 49%, rgba(250,250,250,1) 78%, rgba(250,250,250,1) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#fafafa', GradientType=0 );
    }
</style>

{% if list.latest_question_list %}
    <div class = "results" style="border: solid 1px rgba(255, 0, 0, .03); width:max-content; margin-top: 10px">
        <div class="results"><span class="result_text">Results </span></div>
        <ul>
            {% for question in list.latest_question_list %}
                <li class="_row_results" style="width:max-content">{{ question.question_text }} |XX|
                    {% for choice in question.choice_set.all %}
                        <span>{{ choice.choice_text }} :  {{ choice.votes }} vote{{ choice.votes|pluralize }} </span>   
                    {% endfor %} 
                </li>
            {% endfor %}
        </ul> 
        {% comment %} <a href="{% url 'poll:index' %}">Vote again?</a> {% endcomment %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}